# Generated by Django 5.2.13 on 2026-04-25 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timeline', '0002_alter_timelineevent_options_timelineevent_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the document', max_length=255)),
                ('file', models.FileField(help_text='Document file', upload_to='archive/documents/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('text', 'Text'), ('word', 'Word Document'), ('email', 'Email'), ('other', 'Other')], default='pdf', max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, help_text='Document category (e.g., Contract, Email, Court Filing)', max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for filtering')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extracted metadata (author, date, etc.)')),
                ('description', models.TextField(blank=True, help_text='Description of document contents')),
                ('timeline_event', models.ForeignKey(blank=True, help_text='Linked timeline event (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_documents', to='timeline.timelineevent')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archive Document',
                'verbose_name_plural': 'Archive Documents',
                'ordering': ['-upload_date'],
            },
        ),
    ]
