# Generated by Django 5.2.13 on 2026-04-26 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedocument',
            name='case',
            field=models.ForeignKey(blank=True, help_text='Case this document belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.case'),
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
