# Copyright (C) 2026 Byers Brands, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 5.2.13 on 2026-04-26 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedocument',
            name='case',
            field=models.ForeignKey(blank=True, help_text='Case this document belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.case'),
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
