# Generated by Django 5.2.13 on 2026-04-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_archivedocument_case_archivedocument_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedocument',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('text', 'Text'), ('word', 'Word Document'), ('email', 'Email'), ('other', 'Other')], db_index=True, default='pdf', max_length=20),
        ),
    ]
