# Copyright (C) 2026 Byers Brands, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 5.2.13 on 2026-04-30 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_alter_archivedocument_file_type'),
        ('core', '0004_responsesheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedocument',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Whether this is a draft document (editable)'),
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='is_immutable',
            field=models.BooleanField(default=True, help_text='Read-only to preserve integrity (automatically True for non-drafts)'),
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='path',
            field=models.CharField(blank=True, help_text="Relative path for folder structure (e.g., 'court_documents/subfolder/file.pdf')", max_length=512),
        ),
        migrations.AlterField(
            model_name='archivedocument',
            name='case',
            field=models.ForeignKey(blank=True, help_text='Case this document belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.case'),
        ),
        migrations.CreateModel(
            name='SyncedArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('google_drive', 'Google Drive'), ('local', 'Local Folder')], max_length=50)),
                ('external_path', models.CharField(help_text='GitHub repo URL or local path', max_length=512)),
                ('access_token', models.CharField(blank=True, help_text='For cloud providers', max_length=512)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_configs', to='core.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Synced Archive',
                'verbose_name_plural': 'Synced Archives',
                'ordering': ['-created_at'],
            },
        ),
    ]
