# Generated by Django 5.2.13 on 2026-05-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_archivedocument_is_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedocument',
            name='conversion_error',
            field=models.TextField(blank=True, help_text='Error message if conversion failed'),
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='conversion_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', help_text='Status of PDF to Markdown conversion', max_length=20),
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='markdown_path',
            field=models.CharField(blank=True, help_text='Path to the converted Markdown file', max_length=512),
        ),
    ]
