# Copyright (C) 2026 Byers Brands, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 5.2.13 on 2026-05-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_archivedocument_is_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedocument',
            name='conversion_error',
            field=models.TextField(blank=True, help_text='Error message if conversion failed'),
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='conversion_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', help_text='Status of PDF to Markdown conversion', max_length=20),
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='markdown_path',
            field=models.CharField(blank=True, help_text='Path to the converted Markdown file', max_length=512),
        ),
    ]
