# Generated by Django 5.2.13 on 2026-05-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_archivedocument_conversion_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedocument',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Extracted text content from the document'),
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='text_extraction_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', help_text='Status of text extraction', max_length=20),
        ),
    ]
