# Generated by Django 5.2.13 on 2026-05-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_archivedocument_extracted_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedocument',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('text', 'Text'), ('word', 'Word Document'), ('email', 'Email'), ('folder', 'Folder'), ('other', 'Other')], db_index=True, default='pdf', max_length=20),
        ),
    ]
