# Generated by Django 5.2.13 on 2026-05-02 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_alter_archivedocument_file_type'),
        ('core', '0005_rawdocument_synced_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('dropbox', 'Dropbox'), ('google_drive', 'Google Drive'), ('onedrive', 'OneDrive')], help_text='Cloud storage provider', max_length=50)),
                ('access_token', models.CharField(blank=True, help_text='OAuth2 access token', max_length=512)),
                ('refresh_token', models.CharField(blank=True, help_text='OAuth2 refresh token', max_length=512)),
                ('token_expires', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('folder_path', models.CharField(blank=True, help_text='Path to the folder being imported', max_length=512)),
                ('last_imported', models.DateTimeField(blank=True, help_text='When the last import was performed', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this import is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, help_text='Case this import belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloud_imports', to='core.case')),
                ('user', models.ForeignKey(help_text='User who owns this import', on_delete=django.db.models.deletion.CASCADE, related_name='cloud_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cloud Import',
                'verbose_name_plural': 'Cloud Imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(help_text='Photo file', upload_to='archive/photos/')),
                ('timestamp', models.DateTimeField(blank=True, help_text='Timestamp from EXIF DateTimeOriginal', null=True)),
                ('gps_latitude', models.FloatField(blank=True, help_text='GPS latitude from EXIF', null=True)),
                ('gps_longitude', models.FloatField(blank=True, help_text='GPS longitude from EXIF', null=True)),
                ('device', models.CharField(blank=True, help_text='Device make and model from EXIF', max_length=255)),
                ('sha256_hash', models.CharField(blank=True, help_text='SHA-256 hash for tamper detection', max_length=64)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, help_text='Case this photo belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.case')),
                ('uploader', models.ForeignKey(blank=True, help_text='User who uploaded this photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='CustodyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPLOAD', 'Upload'), ('VIEW', 'View'), ('EDIT', 'Edit'), ('DELETE', 'Delete'), ('EXPORT', 'Export'), ('ANALYZE', 'Analyze'), ('LINK', 'Link to Event'), ('UNLINK', 'Unlink from Event')], help_text='Type of action performed', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent string', max_length=512)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_custody_logs', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(help_text='Photo this action relates to', on_delete=django.db.models.deletion.CASCADE, related_name='custody_logs', to='archive.photo')),
            ],
            options={
                'verbose_name': 'Custody Log',
                'verbose_name_plural': 'Custody Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
