# Generated by Django 5.2.13 on 2026-05-06 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_archivedocument_promotion'),
        ('archive', '0008_cloudimport_photo_custodylog'),
    ]

    operations = [
    ]
