apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres/
  - redis/
  - web/
  - celery/
  - celery-beat/
  - ingress/

configMapGenerator:
  - name: django-config
    files:
      - config/settings_k8s.py
