# Copyright (C) 2026 Byers Brands, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 5.2.13 on 2026-04-25 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the legal case', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the case')),
                ('color', models.CharField(default='#FF8C00', help_text='Color code for UI identification (hex format)', max_length=7)),
                ('is_active', models.BooleanField(default=False, help_text='Whether this is the currently active case')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the case was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the case was last modified')),
                ('user', models.ForeignKey(help_text='User who owns this case', on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-updated_at'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TimelineFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the timeline', max_length=255)),
                ('file_path', models.CharField(help_text='Path to the Markdown file', max_length=512)),
                ('description', models.TextField(blank=True, help_text='Description of what this timeline covers')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the timeline file was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the timeline file was last modified')),
                ('case', models.ForeignKey(blank=True, help_text='Case this timeline belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_files', to='core.case')),
                ('user', models.ForeignKey(help_text='User who owns this timeline', on_delete=django.db.models.deletion.CASCADE, related_name='timeline_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timeline File',
                'verbose_name_plural': 'Timeline Files',
                'ordering': ['-updated_at'],
            },
        ),
    ]
