# Generated by Django 5.2.13 on 2026-04-29 17:12

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(help_text='Name of the legal case', max_length=200),
        ),
        migrations.CreateModel(
            name='RawDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key', primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Uploaded document file', upload_to=apps.core.models.raw_document_upload_path)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('md', 'Markdown'), ('json', 'JSON')], help_text='Type of file (pdf, md, json)', max_length=10)),
                ('source_party', models.CharField(choices=[('CLIENT', 'Client'), ('OPPOSING', 'Opposing Party'), ('NEUTRAL', 'Neutral')], help_text='Who provided the document', max_length=50)),
                ('document_type', models.CharField(help_text='Type of document (e.g., Motion to Dismiss, Contract)', max_length=100)),
                ('reliability_note', models.TextField(blank=True, help_text='Optional notes about document reliability', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the document was uploaded')),
                ('is_immutable', models.BooleanField(default=True, help_text='Whether the document can be modified after creation')),
                ('case', models.ForeignKey(help_text='Case this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='raw_documents', to='core.case')),
            ],
            options={
                'verbose_name': 'Raw Document',
                'verbose_name_plural': 'Raw Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemaRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key', primary_key=True, serialize=False)),
                ('rule_name', models.CharField(help_text='Name of the rule (e.g., timeline_formatting)', max_length=200)),
                ('rule_description', models.TextField(help_text='Description of what the rule does')),
                ('rule_content', models.TextField(help_text='Markdown or JSON rules for LLM formatting')),
                ('case', models.ForeignKey(help_text='Case this rule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='schema_rules', to='core.case')),
            ],
            options={
                'verbose_name': 'Schema Rule',
                'verbose_name_plural': 'Schema Rules',
                'ordering': ['rule_name'],
                'unique_together': {('case', 'rule_name')},
            },
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Page title (e.g., timeline, witness_list)', max_length=200)),
                ('content', models.TextField(help_text='Page content in Markdown')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When the page was last updated')),
                ('version_history', models.JSONField(default=list, help_text='List of previous versions with content and timestamp')),
                ('citation_references', models.JSONField(default=list, help_text='List of claim IDs and their sources')),
                ('case', models.ForeignKey(help_text='Case this wiki page belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='wiki_pages', to='core.case')),
            ],
            options={
                'verbose_name': 'Wiki Page',
                'verbose_name_plural': 'Wiki Pages',
                'ordering': ['-last_updated'],
                'unique_together': {('case', 'title')},
            },
        ),
    ]
