# Generated by Django 5.2.13 on 2026-04-30 21:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_category_to_wikipage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the response sheet (e.g., motion title)', max_length=255)),
                ('source_pdf', models.CharField(blank=True, help_text='Path to source PDF', max_length=512)),
                ('case_number', models.CharField(blank=True, help_text='Case number extracted from PDF', max_length=100)),
                ('state_code', models.CharField(default='IL', help_text='State code (IL, CA, etc.)', max_length=5)),
                ('data', models.JSONField(help_text='Full structured data: metadata, procedural_facts, claims')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the sheet was generated')),
                ('case', models.ForeignKey(blank=True, help_text='Optional case association', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_sheets', to='core.case')),
                ('created_by', models.ForeignKey(help_text='User who generated this sheet', on_delete=django.db.models.deletion.CASCADE, related_name='response_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Response Sheet',
                'verbose_name_plural': 'Response Sheets',
                'ordering': ['-created_at'],
            },
        ),
    ]
