# Generated by Django 5.2.13 on 2026-05-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_responsesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdocument',
            name='synced_at',
            field=models.DateTimeField(blank=True, help_text='When the document was synced to Wiki layer', null=True),
        ),
    ]
