# Generated by Django 5.2.13 on 2026-05-14 22:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rawdocument_synced_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signer_did', models.CharField(help_text='DID of the signer (from OIDC sub claim)', max_length=512)),
                ('signature', models.TextField(help_text='Cryptographic signature returned by the Tauri bridge')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the signature was created')),
                ('document', models.ForeignKey(help_text='The signed evidence document', on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='core.rawdocument')),
            ],
            options={
                'verbose_name': 'Evidence Signature',
                'verbose_name_plural': 'Evidence Signatures',
                'ordering': ['-timestamp'],
            },
        ),
    ]
