# Copyright (C) 2026 Byers Brands, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 5.2.13 on 2026-05-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_evidence_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='client_legal_name',
            field=models.CharField(blank=True, help_text='Full legal name of the client party', max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='opposing_legal_name',
            field=models.CharField(blank=True, help_text='Full legal name of the opposing/adversarial party', max_length=255),
        ),
    ]
