# Generated by Django 5.2.13 on 2026-05-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_evidence_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='client_legal_name',
            field=models.CharField(blank=True, help_text='Full legal name of the client party', max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='opposing_legal_name',
            field=models.CharField(blank=True, help_text='Full legal name of the opposing/adversarial party', max_length=255),
        ),
    ]
