apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: hiver
type: Opaque
data:
  SECRET_KEY: base64-encoded-secret-key
  DB_PASSWORD: base64-encoded-db-password
  EMAIL_HOST_PASSWORD: base64-encoded-email-password
