# Copyright (C) 2026 Byers Brands, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 5.2.13 on 2026-05-02 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_count', models.IntegerField(default=0, help_text='Total number of messages in conversation')),
                ('user_message_count', models.IntegerField(default=0, help_text='Number of messages from user')),
                ('ai_message_count', models.IntegerField(default=0, help_text='Number of messages from AI')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the conversation started')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the conversation ended (null if ongoing)', null=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Duration of conversation in seconds')),
                ('total_characters', models.IntegerField(default=0, help_text='Total characters in all messages')),
                ('user_characters', models.IntegerField(default=0, help_text='Characters from user messages')),
                ('ai_characters', models.IntegerField(default=0, help_text='Characters from AI messages')),
                ('user_rating', models.FloatField(blank=True, help_text='User rating of conversation quality (1-5)', null=True)),
                ('user_feedback', models.TextField(blank=True, help_text='User feedback about the conversation')),
                ('conversation', models.OneToOneField(help_text='The conversation this analytics data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='ai_assistant.aiconversation')),
            ],
            options={
                'verbose_name': 'Conversation Analytics',
                'verbose_name_plural': 'Conversation Analytics',
            },
        ),
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The content of the message')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI Assistant'), ('system', 'System')], default='user', help_text='Who sent this message (user, ai, or system)', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the message was sent')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (e.g., message type, references)')),
                ('conversation', models.ForeignKey(help_text='The AI conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ai_assistant.aiconversation')),
            ],
            options={
                'verbose_name': 'Conversation Log',
                'verbose_name_plural': 'Conversation Logs',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['conversation'], name='conversatio_convers_f7f33b_idx'), models.Index(fields=['timestamp'], name='conversatio_timesta_aa1efd_idx'), models.Index(fields=['sender'], name='conversatio_sender_3eff15_idx')],
            },
        ),
    ]
