# Copyright (C) 2026 Byers Brands, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 5.2.13 on 2026-04-25 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['date'], 'verbose_name': 'Timeline Event', 'verbose_name_plural': 'Timeline Events'},
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='category',
            field=models.CharField(choices=[('contract', 'Contract'), ('email', 'Email'), ('court_filing', 'Court Filing'), ('communication', 'Communication'), ('meeting', 'Meeting'), ('deadline', 'Deadline'), ('other', 'Other')], default='other', help_text='Category of the event', max_length=100),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='date',
            field=models.DateField(help_text='Date of the event'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event',
            field=models.CharField(help_text='Title or name of the event', max_length=255),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='notes',
            field=models.TextField(blank=True, help_text='Detailed notes about the event'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='supporting_docs',
            field=models.JSONField(blank=True, help_text='List of document references (IDs, URLs, or markdown links)', null=True),
        ),
    ]
