# Copyright (C) 2026 Byers Brands, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 5.2.13 on 2026-04-25 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('timeline', '0002_alter_timelineevent_options_timelineevent_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='case',
            field=models.ForeignKey(blank=True, help_text='Case this event belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.case'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='timeline_file',
            field=models.CharField(blank=True, help_text='Path to the Markdown file this event belongs to', max_length=512, null=True),
        ),
    ]
