# Generated by Django 5.2.13 on 2026-04-25 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('timeline', '0002_alter_timelineevent_options_timelineevent_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='case',
            field=models.ForeignKey(blank=True, help_text='Case this event belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.case'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='timeline_file',
            field=models.CharField(blank=True, help_text='Path to the Markdown file this event belongs to', max_length=512, null=True),
        ),
    ]
