# Generated by Django 5.2.13 on 2026-04-30 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_responsesheet'),
        ('timeline', '0003_timelineevent_case_timelineevent_timeline_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='case',
            field=models.ForeignKey(blank=True, help_text='Case this event belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.case'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='date',
            field=models.DateField(db_index=True, help_text='Date of the event'),
        ),
    ]
