# Generated by Django 5.2.13 on 2026-04-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_timelineevent_case_timelineevent_timeline_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='date',
            field=models.DateField(db_index=True, help_text='Date of the event'),
        ),
    ]
