# Copyright (C) 2026 Byers Brands, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 5.2.13 on 2026-04-30 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_responsesheet'),
        ('timeline', '0003_timelineevent_case_timelineevent_timeline_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='case',
            field=models.ForeignKey(blank=True, help_text='Case this event belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.case'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='date',
            field=models.DateField(db_index=True, help_text='Date of the event'),
        ),
    ]
