# Copyright (C) 2026 Byers Brands, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 5.2.13 on 2026-05-02 02:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rawdocument_synced_at'),
        ('timeline', '0004_alter_timelineevent_case_alter_timelineevent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='citation',
            field=models.CharField(blank=True, help_text='Citation or reference for this event', max_length=500),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='source_party',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('OPPOSING', 'Opposing Party'), ('NEUTRAL', 'Neutral')], help_text='Party associated with this event (Client/Opposing/Neutral)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Manual Entry'), ('MARKDOWN', 'Markdown Import'), ('AI_GENERATED', 'AI Generated')], default='MANUAL', help_text='How this event was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='category',
            field=models.CharField(choices=[('verified', 'Verified'), ('contested', 'Contested'), ('contract', 'Contract'), ('email', 'Email'), ('court_filing', 'Court Filing'), ('communication', 'Communication'), ('meeting', 'Meeting'), ('deadline', 'Deadline'), ('personal', 'Personal'), ('legal', 'Legal'), ('medical', 'Medical'), ('financial', 'Financial'), ('education', 'Education'), ('other', 'Other')], default='other', help_text='Category of the event (Verified/Contested/Other)', max_length=100),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='timeline_file',
            field=models.ForeignKey(blank=True, help_text='Source TimelineFile this event was parsed from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='core.timelinefile'),
        ),
        migrations.AlterUniqueTogether(
            name='timelineevent',
            unique_together={('case', 'date', 'event')},
        ),
    ]
