# Generated by Django 5.2.13 on 2026-05-02 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_cloudimport_photo_custodylog'),
        ('timeline', '0005_uuid_pk_and_source_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoEventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(help_text='Confidence score (0-1) for the match')),
                ('notes', models.TextField(blank=True, help_text='AI explanation for the match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='Linked timeline event', on_delete=django.db.models.deletion.CASCADE, related_name='photo_links', to='timeline.timelineevent')),
                ('photo', models.ForeignKey(help_text='Linked photo', on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='archive.photo')),
            ],
            options={
                'verbose_name': 'Photo-Event Link',
                'verbose_name_plural': 'Photo-Event Links',
                'ordering': ['-confidence'],
            },
        ),
    ]
