# Copyright (C) 2026 Byers Brands, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 5.2.13 on 2026-05-02 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_cloudimport_photo_custodylog'),
        ('timeline', '0005_uuid_pk_and_source_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoEventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(help_text='Confidence score (0-1) for the match')),
                ('notes', models.TextField(blank=True, help_text='AI explanation for the match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='Linked timeline event', on_delete=django.db.models.deletion.CASCADE, related_name='photo_links', to='timeline.timelineevent')),
                ('photo', models.ForeignKey(help_text='Linked photo', on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='archive.photo')),
            ],
            options={
                'verbose_name': 'Photo-Event Link',
                'verbose_name_plural': 'Photo-Event Links',
                'ordering': ['-confidence'],
            },
        ),
    ]
