# Generated by Django 5.2.13 on 2026-05-06 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_photoeventlink'),
        ('timeline', '0008_timelineevent_system_source'),
    ]

    operations = [
    ]
