# Generated by Django 5.2.13 on 2026-05-08 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rawdocument_synced_at'),
        ('timeline', '0009_merge_20260506_2347'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='section_header',
            field=models.CharField(blank=True, help_text='Section header this event belongs to (from Markdown ## headers)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='case',
            field=models.ForeignKey(default=None, help_text='Case this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.case'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='category',
            field=models.CharField(choices=[('contract', 'Contract'), ('email', 'Email'), ('court_filing', 'Court Filing'), ('communication', 'Communication'), ('meeting', 'Meeting'), ('deadline', 'Deadline'), ('verified', 'Verified'), ('contested', 'Contested'), ('personal', 'Personal'), ('legal', 'Legal'), ('medical', 'Medical'), ('financial', 'Financial'), ('education', 'Education'), ('other', 'Other')], default='other', help_text='Category of the event', max_length=100),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event',
            field=models.CharField(help_text='Title or name of the event (Event/Incident)', max_length=255),
        ),
    ]
