# Generated by Django 5.2.13 on 2026-05-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0010_add_section_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='last_printed_citation',
            field=models.JSONField(blank=True, help_text='Citation location in last printed PDF: {page_number, row_index}', null=True),
        ),
    ]
