# Copyright (C) 2026 Byers Brands, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 5.2.13 on 2026-04-30 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_responsesheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Conversation', help_text='Title of the conversation', max_length=255)),
                ('messages', models.JSONField(blank=True, default=list, help_text='List of message objects in the conversation')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the conversation was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the conversation was last updated')),
                ('case', models.ForeignKey(blank=True, help_text='Case this conversation belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='core.case')),
                ('user', models.ForeignKey(help_text='User who owns this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Conversation',
                'verbose_name_plural': 'AI Conversations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
