# Generated by Django 5.2.13 on 2026-05-02 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistral_api_key', models.CharField(blank=True, help_text='Mistral AI API key for this user', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the settings were created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the settings were last updated')),
                ('user', models.OneToOneField(help_text='User who owns these settings', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Setting',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
