# Generated by Django 5.2.13 on 2026-05-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Google Gemini API key for this user', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='preferred_ai_provider',
            field=models.CharField(choices=[('mistral', 'Mistral AI'), ('gemini', 'Google Gemini')], default='mistral', help_text='Preferred AI provider for the assistant', max_length=20),
        ),
    ]
